//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorSystemRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorRentalRecord
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOut { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> typeOfMotorId { get; set; }
    
        public virtual TypesOfMotor TypesOfMotor { get; set; }
    }
}
